name: Deploy Staging

on:
  push:
    branches:
      - staging

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Log into GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_REPOSITORY_OWNER }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build & Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          file: ops/staging/Dockerfile
          tags: ghcr.io/${{ secrets.GHCR_REPOSITORY_OWNER }}/custom-shop-staging:latest

      - name: Decode SSH key
        run: |
          echo "${{ secrets.DO_SSH_KEY }}" | base64 --decode > id_rsa
          chmod 600 id_rsa

      - name: Deploy to DigitalOcean
        run: |
          ssh -o StrictHostKeyChecking=no -i id_rsa ${{ secrets.DO_USER }}@${{ secrets.DO_HOST }} "
            cd /var/www/custom-shop-staging &&
            docker-compose pull &&
            docker-compose up -d --remove-orphans
          "
